const WHATSAPP_API_VERSION = process.env.WHATSAPP_API_VERSION || "v23.0";

const WHATSAPP_ACCESS_TOKEN = process.env.WHATSAPP_ACCESS_TOKEN;

const WHATSAPP_PHONE_NUMBER_ID = process.env.WHATSAPP_PHONE_NUMBER_ID;

module.exports = {
  WHATSAPP_API_VERSION,
  WHATSAPP_ACCESS_TOKEN,
  WHATSAPP_PHONE_NUMBER_ID,
};
